### ISSUE TITLE
Status text won't work with MacVim gui

### ISSUE THREAD

**Issue by dbmrq** [tweekmonster/spellrotate.vim#1]
This is really awesome, thank you so much for working on it. :)

I only have one tiny problem when using the MacVim gui and I don't have a clue what's causing it: the status line text shows up the first time and then it doesn't anymore for the next changes at the same word. In the command line it works fine. Any ideas on what could be causing this?
It's not a big deal though, and I'll keep looking into it myself, I just thought I'd mention it in case you have any insights. I'm finding it weird that it only works for the first attempt at each word. Is there anything different happening the first time?

Also this is unrelated, but after trying a lot of mappings I settled on `=s` and `-s`, which are great because they're so close to `]s` and `[s`, and I don't think they're mapped very often. So I thought we could add something like this:

``` vim
if !hasmapto('<Plug>(SpellRotateForward)')
    nmap <unique> =s <Plug>(SpellRotateForward)
    nmap <unique> -s <Plug>(SpellRotateBackward)
    vmap <unique> =s <Plug>(SpellRotateForwardV)
    vmap <unique> -s <Plug>(SpellRotateBackwardV)
endif
```

What do you think?

**Comment by tweekmonster** [comment]
> This is really awesome, thank you so much for working on it. :)

No problem!  It was an interesting problem.  I answer the questions on SE to learn more about Vim, TBH.

> the status line text shows up the first time and then it doesn't anymore

I don't use a GUI client, so I can't test it at the moment.  Try removing the `redraw` at the end of the function and see if that changes it.

I actually want to display the suggestions in the `statusline` but didn't want to deal with defining highlight groups for it.  Since it's a plugin now, I might.

> after trying a lot of mappings I settled on =s and -s

Those maps might make good suggestions in the readme.  `-` is a default motion for moving a line up and I don't want to override any default keys for this plugin.  The spell related maps all suck in my opinion and I don't want to make it more confusing by setting defaults and having an option to disable it.

**Comment by dbmrq** [comment]
Aha, I moved the `redraw` line to just _before_ the first `echon` line and now it works perfectly both in the gui and command line.

Thanks again! ❤️

**Comment by tweekmonster** [comment]
Awesome.  If you want to sit on it to make sure it doesn't add any other weirdness, submit a PR and I'll merge it in the morning.

**Comment by dbmrq** [comment]
Alright, I'll do it soon.
