### ISSUE TITLE
Unexpected behaviour with 'formatoptions+=aw'

### ISSUE THREAD

**Issue by Ram-Z** [tweekmonster/spellrotate.vim#3]
When using the plugin in combination with `formatoptions+=aw`, fixing the spelling sometimes leaves weird artifacts several lines below.

```
To Sherlock Holmes she is always THE woman. I have seldom heard him 
mentio her under any other name. In his eyes she eclipses and 
predominates the whole of her sex. It was not that he felt any emotion 
akin to love for Irene Adler.

# vim:set fo+=aw tw=72 spell:
```

Invoking `<Plug>(SpellRotateForward)` with the cursor on "mentio" on the second line, the text becomes:

```
To Sherlock Holmes she is always THE woman. I have seldom heard
himmention her under any other name. In his eyes she eclipses and
predominates themention whole of her sex. It was not that he felt any
emotion akin to love for Irene Adler.

# vim:set fo+=aw tw=72 spell:
```

Notice the "himmention" on L2, but also "themention" on L3.

I can't figure out exactly when this happens, as for example removing any 2-5 letter word from L3 and fixing "mentio" again will not result in this behaviour.

**Comment by tweekmonster** [comment]
Thanks for the detailed description.  I just made it so that auto format is temporarily disabled during spelling rotation.  Unfortunately, this means you might have to press `=ip` after you're done to reformat the paragraph.  I'll make a note to think of a way to deal with this without disabling auto-format since I think auto-format and quick spelling fixes are useful for literary text.

I've never used the auto format option, but from what `:h auto-format` says, I think it might be because Vim isn't treating all the normal commands in the function as a single atomic change.  The word is deleted to put it in a register, and I think that's when `her` wraps up to the line with `him` and the change marks continue being "wrong" from that point forward.

**Comment by dbmrq** [comment]
Sort of a hack, but maybe you could add an autocommand to run `=ip` and exclude itself right after. Something like this (in a function that would be called after fixing a mistake):

``` vim
let s:saved_ut = &ut
if &ut > 200 | let &ut = 200 | endif
augroup SpellrotateFixAutoformat
    autocmd CursorHold <buffer>
                \ let &ut = s:saved_ut |
                \ normal! =ip |
                \ autocmd! SpellrotateFixAutoformat
augroup END
```

I didn't try it though, just thought I'd mention the possibility.

**Comment by Ram-Z** [comment]
Thanks for the quick response. (and fix)

You mean `gqip`. Re-indenting will not reformat the text. Also since the word replacement will usually have approximately the same length, I don't think the text will need to be reflowed manually often.

The problem with re-formatting unconditionnaly however is that there might be text that should not be reformatted in the paragraph. (like long urls).

**Comment by tweekmonster** [comment]
> You mean `gqip`.

@Ram-Z Oops, yup you're right 😅

> Sort of a hack

@dbmrq I was thinking about this, but as @Ram-Z it might not be worth it and it's best to not remove the user's control over when formatting occurs.

I was able to make a little bit of progress by using `gvc<c-r>='word'<cr>` (instead of `gvp`) which treats it as input text instead of pasted, but the reformatting breaks the expected change marks.  I stopped pursuing this when I realized that a new can of worms will open when dealing with words at the end of the lines.  If a word becomes long enough through a spelling correction, it'll get knocked down to the next line.  Even worse is if the word replacement is two words and the second word gets wrapped.

I'm sure it's possible to get this working by tracking the byte positions in the file, but I prefer to keep this simple.  Missing the opportunity to auto-reformat the paragraph isn't the best outcome, but it's at least an expected outcome that the user can work with.
